import type { GetServerSideProps } from "next";
import { type NextPage } from "next";
import Head from "next/head";
import { signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";
import CreateNote from "../components/CreateNoteModal";
import { useState } from "react";
import { useRouter } from "next/router";
import Image from "next/image";
import { getServerAuthSession } from "../server/common/get-server-auth-session";
import { Button } from "@material-tailwind/react";
import Note from '../components/NoteComponent'
import Navbar from "../components/NavbarComponent";

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getServerAuthSession(context)

  if (!session) {
    return {
      redirect: {
        destination: '/login',
        permanent: false
      }
    }
  }

  return {
    props: {
      session
    }
  }

}



const Home: NextPage = () => {
  const { data: session } = useSession()
  const [open, setOpen] = useState(false)

  const notes = trpc.note.getItems.useQuery()
  const router = useRouter()



  if (!notes.data || notes.isLoading) return <p>Loading...</p>
  if (!session) {
    router.push('/login')
  }
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col w-screen p-1">

        <Navbar>
          <Button size="sm" color="purple" className={`p-2`} onClick={() => setOpen(true)}>Add Note</Button>
          {open && <CreateNote open={open} setOpen={setOpen} notes={notes} />}
          <Button>Teams</Button>
        </Navbar>



        <div className="space-y-6 my-2 w-full lg:grid lg:grid-cols-4 lg:space-y-0 lg:gap-4 p-1">
          {notes.data.sort((a, b) => {
            const one = new Date(b.updatedAt).getTime()
            const two = new Date(a.updatedAt).getTime()
            return one - two
          }).map(item => (
            <Note key={item.id} item={item} notes={notes} />
          ))}
        </div>

      </div >
    </>
  );
};

export default Home;

